### ISSUE TITLE
EXCEPTION CAUGHT BY RENDERING LIBRARY

### ISSUE THREAD

**Issue by yungcloud** [bimsina/wallpaper#3]
Got this Error when changing theme: 

`flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: RenderShrinkWrappingViewport does not support returning intrinsic dimensions.
flutter: Calculating the intrinsic dimensions would require instantiating every child of the viewport, which
flutter: defeats the point of viewports being lazy.
flutter: If you are merely trying to shrink-wrap the viewport in the main axis direction, you should be able
flutter: to achieve that effect by just giving the viewport loose constraints, without needing to measure its
flutter: intrinsic dimensions.
flutter:
flutter: User-created ancestor of the error-causing widget was:
flutter:   AlertDialog file:///Users/m93/AndroidStudioProjects/wallpaper/lib/screens/settings.dart:62:40
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RenderShrinkWrappingViewport.debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1567:9)
flutter: #1      RenderShrinkWrappingViewport.debugThrowIfNotCheckingIntrinsics (package:flutter/src/rendering/viewport.dart:1577:6)
flutter: #2      RenderViewportBase.computeMaxIntrinsicWidth (package:flutter/src/rendering/viewport.dart:321:12)
flutter: #3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1290:23)
flutter: #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
flutter: #5      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1288:41)
flutter: #6      RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1476:12)
flutter: #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:77:20)
flutter: #8      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1290:23)
flutter: #9      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
flutter: #10     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1288:41)
flutter: #11     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1476:12)
flutter: #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:77:20)
flutter: #13     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1290:23)
flutter: #14     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
flutter: #15     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1288:41)
flutter: #16     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1476:12)
flutter: #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:77:20)
flutter: #18     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1290:23)
flutter: #19     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
flutter: #20     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1288:41)
flutter: #21     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1476:12)
flutter: #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:77:20)
flutter: #23     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1290:23)
flutter: #24     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
flutter: #25     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1288:41)
flutter: #26     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1476:12)
flutter: #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:77:20)
flutter: #28     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1290:23)
flutter: #29     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
flutter: #30     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1288:41)
flutter: #31     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1476:12)
flutter: #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:77:20)
flutter: #33     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1290:23)
flutter: #34     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
flutter: #35     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1288:41)
flutter: #36     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1476:12)
flutter: #37     RenderShiftedBox.computeMaxIntrinsicWidth (package:flutter/src/rendering/shifted_box.dart:33:20)
flutter: #38     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1290:23)
flutter: #39     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
flutter: #40     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1288:41)
flutter: #41     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1476:12)
flutter: #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:77:20)
flutter: #43     RenderConstrainedBox.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:227:32)
flutter: #44     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1290:23)
flutter: #45     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
flutter: #46     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1288:41)
flutter: #47     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1476:12)
flutter: #48     RenderPadding.computeMaxIntrinsicWidth (package:flutter/src/rendering/shifted_box.dart:170:20)
flutter: #49     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1290:23)
flutter: #50     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
flutter: #51     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1288:41)
flutter: #52     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1476:12)
flutter: #53     RenderFlex.computeMaxIntrinsicWidth.<anonymous closure> (package:flutter/src/rendering/flex.dart:577:60)
flutter: #54     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:554:58)
flutter: #55     RenderFlex.computeMaxIntrinsicWidth (package:flutter/src/rendering/flex.dart:574:12)
flutter: #56     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1290:23)
flutter: #57     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
flutter: #58     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1288:41)
flutter: #59     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1476:12)
flutter: #60     RenderIntrinsicWidth.performLayout (package:flutter/src/rendering/proxy_box.dart:631:36)
flutter: #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #67     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
flutter: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #69     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
flutter: #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #71     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392:13)
flutter: #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #73     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
flutter: #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #75     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
flutter: #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #77     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #79     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #83     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #85     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #87     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #89     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #90     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3076:13)
flutter: #91     RenderObject.layout (package:flutter/src/rendering/object.dart:1639:7)
flutter: #92     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #93     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1516:7)
flutter: #94     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:783:18)
flutter: #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
flutter: #96     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:702:13)
flutter: #97     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
flutter: #98     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
flutter: #99     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
flutter: #100    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
flutter: #104    _invoke (dart:ui/hooks.dart:236:10)
flutter: #105    _drawFrame (dart:ui/hooks.dart:194:3)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderIntrinsicWidth#fb94d relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   creator: IntrinsicWidth ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
flutter:     _InkFeatures-[GlobalKey#edab1 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
flutter:     CustomPaint ← _ShapeBorderPaint ← PhysicalShape ← _MaterialInterior ← Material ← ConstrainedBox ←
flutter:     Center ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(280.0<=w<=295.0, 0.0<=h<=599.0)
flutter:   size: MISSING
flutter:   stepWidth: null
flutter:   stepHeight: null
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     child: RenderFlex#7f417 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child 1: RenderPadding#8ff72 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child: RenderSemanticsAnnotations#78aa1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderParagraph#0106b NEEDS-LAYOUT NEEDS-PAINT
flutter:             text: TextSpan
flutter:       child 2: RenderPadding#baa2c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child: RenderConstrainedBox#52148 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderPositionedBox#90bb7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: _RenderScrollSemantics#49c80 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: RenderBox was not laid out: RenderIntrinsicWidth#fb94d relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#19ed3 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#6bc9e relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#e6f28 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 321 pos 12: 'child.hasSize': is not true.
flutter: Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#e6f28 relayoutBoundary=up2`

**Comment by yungcloud** [comment]
fixed by giving **"content: SizedBox("** a **width**, along with **height**. on settings.dart line 68
